import {
  type BookTheme,
  type CreateProjectInput,
  type PhotoAsset,
  type Project,
  type ProjectInvite,
  type ProjectMember,
  type ProjectSummary,
} from "./types";
import { normalizeProjectDraftState } from "./editorial";

const editorialThemes: BookTheme[] = [
  {
    id: "golden-hour",
    name: "Golden Hour",
    mood: "Warm travel editorial",
    accent: "#c76c3a",
    typeface: "Cormorant Garamond + Manrope",
  },
  {
    id: "pine-ink",
    name: "Pine & Ink",
    mood: "Clean outdoor journal",
    accent: "#335c52",
    typeface: "Fraunces + Inter",
  },
  {
    id: "coastline",
    name: "Coastline",
    mood: "Soft premium album",
    accent: "#6a7ea8",
    typeface: "Newsreader + Satoshi",
  },
];

const sharedMembers: ProjectMember[] = [
  {
    id: "vince",
    name: "Vince",
    email: "vince@example.com",
    role: "owner",
    avatarLabel: "V",
    homeBase: "Denver, Colorado",
  },
  {
    id: "emma",
    name: "Emma",
    email: "emma@example.com",
    role: "collaborator",
    avatarLabel: "E",
    homeBase: "Fort Collins, Colorado",
  },
];

function commonsImage(fileName: string) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=1600`;
}

function seededImage(seed: string, width = 1600, height = 1200) {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/${width}/${height}`;
}

function cloneThemes() {
  return editorialThemes.map((theme) => ({ ...theme }));
}

function cloneMembers() {
  return sharedMembers.map((member) => ({ ...member }));
}

function photo(
  input: Omit<PhotoAsset, "versions"> & { dimensions: [number, number] },
): PhotoAsset {
  const [width, height] = input.dimensions;

  return {
    id: input.id,
    title: input.title,
    uploaderId: input.uploaderId,
    imageUri: input.imageUri,
    storagePath: input.storagePath,
    mimeType: input.mimeType,
    capturedAt: input.capturedAt,
    locationLabel: input.locationLabel,
    locationConfidence: input.locationConfidence,
    orientation: input.orientation,
    mustInclude: input.mustInclude,
    approved: input.approved,
    peopleIds: input.peopleIds,
    faceClusterIds: input.faceClusterIds,
    qualityNotes: input.qualityNotes,
    versions: [
      {
        id: `${input.id}-original`,
        label: "original",
        status: "ready",
        width,
        height,
      },
      {
        id: `${input.id}-enhanced`,
        label: "enhanced",
        status: "ready",
        width,
        height,
      },
      {
        id: `${input.id}-preview`,
        label: "preview",
        status: "ready",
        width: Math.round(width / 2),
        height: Math.round(height / 2),
      },
    ],
  };
}

function buildAcceptedInvites(members: ProjectMember[]): ProjectInvite[] {
  return members.map((member) => ({
    id: `invite-${member.id}`,
    name: member.name,
    email: member.email,
    role: member.role,
    status: "accepted",
    sentAt: "2026-03-02T18:00:00.000Z",
    acceptedAt: "2026-03-02T18:05:00.000Z",
    acceptedByUserId: member.id,
  }));
}

function seededPhoto(
  input: Omit<PhotoAsset, "imageUri" | "versions"> & {
    dimensions: [number, number];
    seed: string;
  },
): PhotoAsset {
  const [width, height] = input.dimensions;

  return photo({
    ...input,
    imageUri: seededImage(input.seed, width, height),
    dimensions: input.dimensions,
  });
}

export function createSeedProjects(): Project[] {
  const weekendTrip: Project = {
    id: "yellowstone-weekend",
    type: "trip",
    title: "Yellowstone Weekend",
    subtitle: "Steam, campfire smoke, and the first bear sighting of the year.",
    status: "needs_resolution",
    timezone: "America/Denver",
    startDate: "2026-05-14",
    endDate: "2026-05-17",
    ownerId: "vince",
    members: cloneMembers(),
    invites: buildAcceptedInvites(sharedMembers),
    notes: [
      {
        id: "note-1",
        authorId: "vince",
        title: "Arrival mood",
        body: "We made it just before sunset and the sky turned orange behind the steam pools.",
        createdAt: "2026-05-14T23:40:00.000Z",
      },
      {
        id: "note-2",
        authorId: "emma",
        title: "Morning checklist",
        body: "Coffee, fog, and that ridiculous elk traffic jam outside the campsite.",
        createdAt: "2026-05-15T14:12:00.000Z",
      },
    ],
    photos: [
      photo({
        id: "photo-1",
        title: "Grand Prismatic from above",
        uploaderId: "vince",
        imageUri: commonsImage("Grand prismatic spring edit.jpg"),
        capturedAt: "2026-05-14T19:21:00.000Z",
        locationLabel: "Grand Prismatic Spring",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: true,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-1", "cluster-2"],
        qualityNotes: ["Needs slight horizon correction."],
        dimensions: [2400, 1600],
      }),
      photo({
        id: "photo-2",
        title: "Splendid Geyser portrait",
        uploaderId: "emma",
        imageUri: commonsImage("Splendid geyser yellowstone national park.jpg"),
        capturedAt: "2026-05-14T22:47:00.000Z",
        locationLabel: "Splendid Geyser",
        locationConfidence: "inferred",
        orientation: "portrait",
        mustInclude: true,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["Low light rescue queued."],
        dimensions: [1600, 2200],
      }),
      photo({
        id: "photo-3",
        title: "Bison at dawn",
        uploaderId: "vince",
        imageUri: commonsImage("American bison in Yellowstone National Park.jpg"),
        capturedAt: "2026-05-15T08:10:00.000Z",
        locationLabel: undefined,
        locationConfidence: "missing",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Waiting on location confirmation."],
        dimensions: [2600, 1600],
      }),
      photo({
        id: "photo-4",
        title: "Old Faithful in evening light",
        uploaderId: "emma",
        imageUri: commonsImage(
          "Yellowstone National Park (WY, USA), Old Faithful Geyser -- 2022 -- 2589.jpg",
        ),
        capturedAt: "2026-05-15T11:52:00.000Z",
        locationLabel: "Old Faithful",
        locationConfidence: "exact",
        orientation: "square",
        mustInclude: true,
        approved: false,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-1", "cluster-2"],
        qualityNotes: ["Marked for hero opener."],
        dimensions: [1800, 1800],
      }),
      photo({
        id: "photo-5",
        title: "Lower Falls overlook",
        uploaderId: "vince",
        imageUri: commonsImage("Yellowstone Lower Falls.jpg"),
        capturedAt: "2026-05-16T17:25:00.000Z",
        locationLabel: "Artist Point",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["vince"],
        faceClusterIds: ["cluster-1"],
        qualityNotes: ["Ready for balanced spread."],
        dimensions: [2400, 1600],
      }),
      seededPhoto({
        id: "photo-6",
        title: "Camp coffee at Madison",
        uploaderId: "emma",
        seed: "yellowstone-camp-coffee",
        capturedAt: "2026-05-15T13:18:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["Perfect support frame for a quieter details spread."],
        dimensions: [1600, 1200],
      }),
      seededPhoto({
        id: "photo-7",
        title: "Boardwalk texture study",
        uploaderId: "vince",
        seed: "yellowstone-boardwalk-texture",
        capturedAt: "2026-05-15T15:02:00.000Z",
        locationLabel: "Upper Geyser Basin",
        locationConfidence: "inferred",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Small detail that works better in a grid than as a hero image."],
        dimensions: [1400, 1400],
      }),
      seededPhoto({
        id: "photo-8",
        title: "Mammoth terrace detail",
        uploaderId: "emma",
        seed: "yellowstone-terrace-detail",
        capturedAt: "2026-05-16T09:24:00.000Z",
        locationLabel: "Mammoth Hot Springs",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["A good texture-led portrait to break up the wide landscapes."],
        dimensions: [1500, 2000],
      }),
      seededPhoto({
        id: "photo-9",
        title: "Yellowstone Lake morning",
        uploaderId: "vince",
        seed: "yellowstone-lake-morning",
        capturedAt: "2026-05-16T11:12:00.000Z",
        locationLabel: "Yellowstone Lake",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: true,
        approved: true,
        peopleIds: ["vince"],
        faceClusterIds: ["cluster-1"],
        qualityNotes: ["This should have enough room to function as a hero landscape."],
        dimensions: [2200, 1500],
      }),
      seededPhoto({
        id: "photo-10",
        title: "Trail marker and lodgepoles",
        uploaderId: "vince",
        seed: "yellowstone-trail-marker",
        capturedAt: "2026-05-16T14:46:00.000Z",
        locationLabel: "West Thumb",
        locationConfidence: "inferred",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Useful as a place-setting image between bigger scenic pages."],
        dimensions: [1500, 2100],
      }),
      seededPhoto({
        id: "photo-11",
        title: "Campfire after dark",
        uploaderId: "emma",
        seed: "yellowstone-campfire-dark",
        capturedAt: "2026-05-16T22:04:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-1", "cluster-2"],
        qualityNotes: ["Pairs well with handwritten-note or journal-led closers."],
        dimensions: [1800, 1200],
      }),
      seededPhoto({
        id: "photo-12",
        title: "Sunrise fog in Hayden Valley",
        uploaderId: "vince",
        seed: "yellowstone-hayden-fog",
        capturedAt: "2026-05-15T06:42:00.000Z",
        locationLabel: "Hayden Valley",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Use as a support scenic, not the cover hero."],
        dimensions: [2100, 1400],
      }),
      seededPhoto({
        id: "photo-13",
        title: "Black Sand Basin boardwalk",
        uploaderId: "emma",
        seed: "yellowstone-black-sand-boardwalk",
        capturedAt: "2026-05-15T10:11:00.000Z",
        locationLabel: "Black Sand Basin",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["Works best as a vertical support frame."],
        dimensions: [1600, 2200],
      }),
      seededPhoto({
        id: "photo-14",
        title: "Picnic table breakfast spread",
        uploaderId: "emma",
        seed: "yellowstone-picnic-breakfast",
        capturedAt: "2026-05-15T08:56:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-1", "cluster-2"],
        qualityNotes: ["A good human-scale support image."],
        dimensions: [2000, 1400],
      }),
      seededPhoto({
        id: "photo-15",
        title: "Lamar Valley turnout",
        uploaderId: "vince",
        seed: "yellowstone-lamar-turnout",
        capturedAt: "2026-05-16T07:28:00.000Z",
        locationLabel: "Lamar Valley",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Adds route context to wildlife sequences."],
        dimensions: [2200, 1500],
      }),
      seededPhoto({
        id: "photo-16",
        title: "Thermal runoff close-up",
        uploaderId: "emma",
        seed: "yellowstone-thermal-runoff",
        capturedAt: "2026-05-15T12:04:00.000Z",
        locationLabel: "Midway Geyser Basin",
        locationConfidence: "inferred",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Texture grid material."],
        dimensions: [1500, 1500],
      }),
      seededPhoto({
        id: "photo-17",
        title: "Canyon rim pines",
        uploaderId: "vince",
        seed: "yellowstone-canyon-pines",
        capturedAt: "2026-05-16T16:12:00.000Z",
        locationLabel: "North Rim",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Good counterweight to waterfall scenery."],
        dimensions: [1600, 2200],
      }),
      seededPhoto({
        id: "photo-18",
        title: "Mud pot bubbles",
        uploaderId: "emma",
        seed: "yellowstone-mudpot-bubbles",
        capturedAt: "2026-05-15T12:31:00.000Z",
        locationLabel: "Artists' Paintpots",
        locationConfidence: "exact",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Small detail for a dense candid grid."],
        dimensions: [1400, 1400],
      }),
      seededPhoto({
        id: "photo-19",
        title: "Wildflower beside the basin",
        uploaderId: "emma",
        seed: "yellowstone-wildflower-basin",
        capturedAt: "2026-05-15T13:42:00.000Z",
        locationLabel: "Upper Geyser Basin",
        locationConfidence: "inferred",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Quiet transition photo."],
        dimensions: [1500, 2100],
      }),
      seededPhoto({
        id: "photo-20",
        title: "Cabin mirror selfie",
        uploaderId: "emma",
        seed: "yellowstone-mirror-selfie",
        capturedAt: "2026-05-16T18:44:00.000Z",
        locationLabel: "Old Faithful Inn",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-1", "cluster-2"],
        qualityNotes: ["Not hero quality, but strong memory value."],
        dimensions: [1600, 2200],
      }),
      seededPhoto({
        id: "photo-21",
        title: "Roadside elk pause",
        uploaderId: "vince",
        seed: "yellowstone-roadside-elk",
        capturedAt: "2026-05-16T07:46:00.000Z",
        locationLabel: "Lamar Valley",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Another wildlife context frame."],
        dimensions: [2200, 1500],
      }),
      seededPhoto({
        id: "photo-22",
        title: "Bridge over the Firehole",
        uploaderId: "vince",
        seed: "yellowstone-firehole-bridge",
        capturedAt: "2026-05-15T17:05:00.000Z",
        locationLabel: "Firehole River",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Good route-marker support shot."],
        dimensions: [2000, 1400],
      }),
      seededPhoto({
        id: "photo-23",
        title: "S'mores supplies on the bench",
        uploaderId: "emma",
        seed: "yellowstone-smores-supplies",
        capturedAt: "2026-05-16T21:18:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Memorabilia spread filler."],
        dimensions: [1500, 1500],
      }),
      seededPhoto({
        id: "photo-24",
        title: "Morning tent zipper",
        uploaderId: "vince",
        seed: "yellowstone-tent-zipper",
        capturedAt: "2026-05-16T06:55:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Adds first-person trip texture."],
        dimensions: [1500, 2200],
      }),
      seededPhoto({
        id: "photo-25",
        title: "Trail snack stop",
        uploaderId: "emma",
        seed: "yellowstone-trail-snack-stop",
        capturedAt: "2026-05-16T15:21:00.000Z",
        locationLabel: "Uncle Tom's Trail",
        locationConfidence: "inferred",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["A human-scale detail shot."],
        dimensions: [2000, 1400],
      }),
      seededPhoto({
        id: "photo-26",
        title: "Geyser plume through trees",
        uploaderId: "vince",
        seed: "yellowstone-plume-through-trees",
        capturedAt: "2026-05-15T11:14:00.000Z",
        locationLabel: "Old Faithful Basin",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Good for a burst or repetition spread."],
        dimensions: [2200, 1500],
      }),
      seededPhoto({
        id: "photo-27",
        title: "Lodge window at blue hour",
        uploaderId: "emma",
        seed: "yellowstone-lodge-window-blue-hour",
        capturedAt: "2026-05-16T20:05:00.000Z",
        locationLabel: "Old Faithful Inn",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Night detail for the final act."],
        dimensions: [1500, 2100],
      }),
      seededPhoto({
        id: "photo-28",
        title: "Thermos on the railing",
        uploaderId: "vince",
        seed: "yellowstone-thermos-railing",
        capturedAt: "2026-05-16T06:58:00.000Z",
        locationLabel: "Yellowstone Lake",
        locationConfidence: "inferred",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Small quiet still-life."],
        dimensions: [1500, 1500],
      }),
      seededPhoto({
        id: "photo-29",
        title: "Yellowstone River bend",
        uploaderId: "vince",
        seed: "yellowstone-river-bend",
        capturedAt: "2026-05-16T10:03:00.000Z",
        locationLabel: "Yellowstone River",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Support landscape for the midpoint scenic act."],
        dimensions: [2200, 1500],
      }),
      seededPhoto({
        id: "photo-30",
        title: "Wet boots by the tent",
        uploaderId: "emma",
        seed: "yellowstone-wet-boots-tent",
        capturedAt: "2026-05-16T07:08:00.000Z",
        locationLabel: "Madison Campground",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["Object-level memory for the camp section."],
        dimensions: [1500, 2100],
      }),
      seededPhoto({
        id: "photo-31",
        title: "Parking lot raven",
        uploaderId: "vince",
        seed: "yellowstone-parking-lot-raven",
        capturedAt: "2026-05-17T08:14:00.000Z",
        locationLabel: "Canyon Village",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: false,
        approved: true,
        peopleIds: [],
        faceClusterIds: [],
        qualityNotes: ["A slightly odd closer detail."],
        dimensions: [1500, 2100],
      }),
      seededPhoto({
        id: "photo-32",
        title: "Last look at the basin",
        uploaderId: "emma",
        seed: "yellowstone-last-look-basin",
        capturedAt: "2026-05-17T09:26:00.000Z",
        locationLabel: "Upper Geyser Basin",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: false,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-2"],
        qualityNotes: ["Strong closing support landscape."],
        dimensions: [2200, 1500],
      }),
    ],
    faceClusters: [
      {
        id: "cluster-1",
        suggestedMemberId: "vince",
        confidence: 0.94,
        status: "mapped",
        thumbnailPhotoId: "photo-1",
      },
      {
        id: "cluster-2",
        suggestedMemberId: "emma",
        confidence: 0.92,
        status: "mapped",
        thumbnailPhotoId: "photo-2",
      },
      {
        id: "cluster-3",
        confidence: 0.61,
        status: "unknown",
        thumbnailPhotoId: "photo-3",
      },
    ],
    resolutionTasks: [
      {
        id: "task-1",
        type: "location",
        title: "Confirm elk crossing location",
        detail: "The sunrise wildlife shot has no GPS data and needs a manual park stop.",
        status: "open",
        dueLabel: "Needed before book export",
        assigneeIds: ["vince", "emma"],
      },
      {
        id: "task-2",
        type: "people",
        title: "Check unknown face cluster",
        detail: "The clustering pass found one more face candidate in the trail recap sequence.",
        status: "in_progress",
        dueLabel: "Today",
        assigneeIds: ["emma"],
      },
    ],
    bookThemes: cloneThemes(),
    selectedThemeId: "golden-hour",
    bookDraft: {
      id: "draft-1",
      title: "Yellowstone Weekend",
      format: "12x12 square",
      status: "reviewing",
      themeId: "golden-hour",
      summary:
        "A fuller Yellowstone stress-test draft with thirty-two photos, scenic resets, dense detail sequences, and a softer final act that still reads like a curated album instead of a camera roll export.",
      pages: [
        {
          id: "page-1",
          style: "hero_support_strip",
          storyBeat: "opener",
          title: "We arrived with the steam already glowing.",
          caption:
            "The opener should land on one strong frame, then quietly establish the steam and boardwalk textures that kept the first evening from feeling generic.",
          copyStatus: "confirmed",
          copySource: "hybrid",
          photoIds: ["photo-4", "photo-12", "photo-13"],
          layoutNote: "Lead with the square geyser portrait, then let two support frames establish steam and route context.",
          curationNote:
            "The book should feel cinematic from page one, not like a dump of the first three photos from the trip.",
          approved: true,
        },
        {
          id: "page-2",
          style: "balanced_two_up",
          storyBeat: "scene_setter",
          title: "Madison felt personal before it felt scenic.",
          caption:
            "A paired spread of camp breakfast and the first big basin view keeps the trip grounded in people-scale moments before the wider scenic run.",
          copyStatus: "prefilled",
          copySource: "metadata",
          photoIds: ["photo-2", "photo-1", "photo-14"],
          layoutNote: "Keep the portrait and scenic frame balanced, then let the breakfast photo act as a smaller support note.",
          curationNote:
            "This should feel like a real edit decision, not two random favorites placed beside each other.",
          approved: false,
        },
        {
          id: "page-3",
          style: "dense_candid_grid",
          storyBeat: "details",
          title: "The basin details deserved their own rhythm.",
          caption:
            "Textures, runoff, mud pots, flowers, and the boardwalk all belong together on one denser page so the detail work does not interrupt the bigger scenic pacing.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-6", "photo-7", "photo-16", "photo-18", "photo-19"],
          layoutNote: "Use a tight grid with small gutters so the page reads as a collected detail study.",
          curationNote:
            "Grouping this material into one grid makes the book feel intentional instead of constantly stopping for one-off closeups.",
          approved: false,
        },
        {
          id: "page-4",
          style: "panorama_spread",
          storyBeat: "highlight",
          title: "The lake morning needed room to breathe.",
          caption:
            "This is the midpoint reset where the book should exhale and let the wides do most of the work.",
          copyStatus: "confirmed",
          copySource: "hybrid",
          photoIds: ["photo-9", "photo-29"],
          layoutNote: "Treat this as a scenic reset with minimal copy and lots of uninterrupted image area.",
          curationNote:
            "A real book needs quiet spreads, not relentless density.",
          approved: true,
        },
        {
          id: "page-5",
          style: "balanced_two_up",
          storyBeat: "highlight",
          title: "The canyon stretch needed both scale and pause.",
          caption:
            "One scenic frame and one vertical pine study keep the canyon sequence from becoming another all-landscape spread.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-5", "photo-17", "photo-15"],
          layoutNote: "Keep the scenic image dominant and let the vertical tree frame slow the pacing down.",
          curationNote:
            "The best scenic sections still need one image that changes the texture of the sequence.",
          approved: false,
        },
        {
          id: "page-6",
          style: "photo_journal",
          storyBeat: "reflection",
          title: "The in-between human moments carried the trip.",
          caption:
            "The mirror selfie, s'mores supplies, and the first unzip of the tent are not technically perfect, but they are exactly what makes the trip feel like ours.",
          copyStatus: "prefilled",
          copySource: "note",
          photoIds: ["photo-20", "photo-23", "photo-24"],
          layoutNote: "Use one lead image with journal-style supporting moments rather than treating these like a formal scenic page.",
          curationNote:
            "Some imperfect phone-like images should survive if they carry the emotional memory of the trip.",
          approved: false,
        },
        {
          id: "page-7",
          style: "memorabilia_spread",
          storyBeat: "details",
          title: "Camp details made the whole weekend tactile.",
          caption:
            "Objects and surfaces should sit together here so the campground reads like a place, not just a place to sleep between scenic stops.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-11", "photo-22", "photo-25", "photo-30"],
          layoutNote: "Keep the campfire or bridge image larger and let the boots and snack details fill the lower rhythm.",
          curationNote:
            "This is the kind of page that makes the finished book feel kept, not merely organized.",
          approved: false,
        },
        {
          id: "page-8",
          style: "burst_sequence",
          storyBeat: "details",
          title: "The strange little evening frames belonged together.",
          caption:
            "The plume, lodge window, thermos, and raven all feel like fragments on their own, but as a sequence they start to read like the trip winding down.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-26", "photo-27", "photo-28", "photo-31"],
          layoutNote: "Keep the first frame dominant and let the others step down in size like a soft visual sequence.",
          curationNote:
            "Repetition and cadence work better here than four equal boxes.",
          approved: false,
        },
        {
          id: "page-9",
          style: "map_timeline",
          storyBeat: "reflection",
          title: "The wildlife leg changed the route of the whole day.",
          caption:
            "This spread should connect the wildlife stop, the turnouts, and the last basin drive so the book still feels like a trip with movement, not just a stack of places.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-3", "photo-15", "photo-21", "photo-32"],
          layoutNote: "Let the route context and one hero wildlife image do the heavy lifting here.",
          curationNote:
            "Travel books get stronger when the route is explicit instead of implied.",
          approved: false,
        },
        {
          id: "page-10",
          style: "closing",
          storyBeat: "closing",
          title: "The trip ended quieter than it started.",
          caption:
            "The last pages should feel like a gentle release instead of one more attempt at spectacle, with enough air that the sequence can finally land.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["photo-9", "photo-32", "photo-29"],
          layoutNote: "Use more whitespace here than anywhere else in the book.",
          curationNote:
            "The close should feel remembered, not performed.",
          approved: false,
        },
      ],
    },
    mockPrintOrder: {
      id: "order-1",
      status: "reviewing",
      priceCents: 6800,
      shippingName: "Vince Hernandez",
      shippingCity: "Denver, CO",
      estimatedShipWindow: "5-7 business days",
      orderCode: "PBM-YS-2048",
    },
  };

  const yearbook: Project = {
    id: "yearbook-2026",
    type: "yearbook",
    title: "Our 2026 Yearbook",
    subtitle: "Every road trip, rainy walk, and accidental perfect photo from the year.",
    status: "reviewing",
    timezone: "America/Denver",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    year: 2026,
    yearbookCycle: "calendar_year",
    ownerId: "vince",
    members: cloneMembers(),
    invites: buildAcceptedInvites(sharedMembers),
    notes: [
      {
        id: "note-y-1",
        authorId: "emma",
        title: "What this year felt like",
        body: "Lots of quick trips, many coffees, and the kind of photos that feel casual until you see them together.",
        createdAt: "2026-09-03T19:15:00.000Z",
      },
    ],
    photos: [
      photo({
        id: "year-photo-1",
        title: "Rainy city walk",
        uploaderId: "emma",
        capturedAt: "2026-02-21T17:00:00.000Z",
        locationLabel: "Seattle waterfront",
        locationConfidence: "exact",
        orientation: "portrait",
        mustInclude: true,
        approved: true,
        peopleIds: ["emma"],
        faceClusterIds: ["cluster-y-1"],
        qualityNotes: ["Good for a quiet page transition."],
        dimensions: [1600, 2200],
      }),
      photo({
        id: "year-photo-2",
        title: "Canyon overlook",
        uploaderId: "vince",
        capturedAt: "2026-06-18T18:32:00.000Z",
        locationLabel: "Moab",
        locationConfidence: "exact",
        orientation: "landscape",
        mustInclude: true,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-y-1", "cluster-y-2"],
        qualityNotes: ["Full-bleed spread candidate."],
        dimensions: [2400, 1600],
      }),
      photo({
        id: "year-photo-3",
        title: "Cabin breakfast",
        uploaderId: "emma",
        capturedAt: "2026-11-09T09:41:00.000Z",
        locationLabel: "Rocky Mountain cabin",
        locationConfidence: "inferred",
        orientation: "square",
        mustInclude: false,
        approved: true,
        peopleIds: ["vince", "emma"],
        faceClusterIds: ["cluster-y-1", "cluster-y-2"],
        qualityNotes: ["Needs caption polish."],
        dimensions: [1900, 1900],
      }),
    ],
    faceClusters: [
      {
        id: "cluster-y-1",
        suggestedMemberId: "emma",
        confidence: 0.91,
        status: "mapped",
        thumbnailPhotoId: "year-photo-1",
      },
      {
        id: "cluster-y-2",
        suggestedMemberId: "vince",
        confidence: 0.93,
        status: "mapped",
        thumbnailPhotoId: "year-photo-2",
      },
    ],
    resolutionTasks: [],
    bookThemes: cloneThemes(),
    selectedThemeId: "coastline",
    bookDraft: {
      id: "draft-2",
      title: "Our 2026 Yearbook",
      format: "12x12 square",
      status: "reviewing",
      themeId: "coastline",
      summary:
        "A softer annual rhythm with one cinematic summer spread, quiet interludes, and recap captions built from your notes.",
      pages: [
        {
          id: "page-y-1",
          style: "hero",
          storyBeat: "opener",
          title: "A year told in little escapes.",
          caption:
            "Open with the strongest portrait, then let the rest of the year unfurl around it.",
          copyStatus: "confirmed",
          copySource: "hybrid",
          photoIds: ["year-photo-1"],
          layoutNote: "Use a large serif opener and tight copy block.",
          curationNote:
            "The opener frames the whole year in one restrained image before the book expands into bigger moments.",
          approved: true,
        },
        {
          id: "page-y-2",
          style: "full_bleed",
          storyBeat: "highlight",
          title: "Summer needed a full spread.",
          caption:
            "The canyon overlook carries the whole middle act, with enough margin on the caption to keep it premium.",
          copyStatus: "confirmed",
          copySource: "metadata",
          photoIds: ["year-photo-2"],
          layoutNote: "Full-bleed landscape with a restrained lower-third caption.",
          curationNote:
            "Reserve the single-image cinematic spread for the frame that can carry a whole season by itself.",
          approved: true,
        },
        {
          id: "page-y-3",
          style: "mosaic",
          storyBeat: "reflection",
          title: "The cozy part of the year",
          caption:
            "Pair smaller moments late in the book so the annual story ends warm instead of busy.",
          copyStatus: "prefilled",
          copySource: "hybrid",
          photoIds: ["year-photo-3", "year-photo-1"],
          layoutNote: "Two-photo collage with asymmetrical whitespace.",
          curationNote:
            "Late-book detail pages should feel warm and gathered, not like leftover images filling space.",
          approved: false,
        },
      ],
    },
    mockPrintOrder: {
      id: "order-2",
      status: "draft",
      priceCents: 8200,
      shippingName: "Emma Walker",
      shippingCity: "Fort Collins, CO",
      estimatedShipWindow: "6-8 business days",
      orderCode: "PBM-YB-2026",
    },
  };

  return [normalizeProjectDraftState(weekendTrip), normalizeProjectDraftState(yearbook)];
}

export function getProjectSummary(project: Project): ProjectSummary {
  return {
    approvedPhotos: project.photos.filter((entry) => entry.approved).length,
    mustIncludePhotos: project.photos.filter((entry) => entry.mustInclude).length,
    openTasks: project.resolutionTasks.filter((task) => task.status !== "resolved").length,
    acceptedInvites: project.invites.filter((invite) => invite.status === "accepted").length,
    pageCount: project.bookDraft.pages.length,
  };
}

export function createMockProject(input: CreateProjectInput): Project {
  const owner: ProjectMember = {
    id: "owner-generated",
    name: input.ownerName,
    email: input.ownerEmail,
    role: "owner",
    avatarLabel: input.ownerName.slice(0, 1).toUpperCase(),
    homeBase: "To be added",
  };

  const titleSeed = input.title
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  return normalizeProjectDraftState({
    id: `${input.type}-${titleSeed || "new-project"}`,
    type: input.type,
    title: input.title,
    subtitle: input.subtitle,
    status: "collecting",
    timezone: input.timezone,
    startDate: input.startDate,
    endDate: input.endDate,
    year: input.type === "yearbook" ? Number(input.startDate.slice(0, 4)) : undefined,
    yearbookCycle: input.type === "yearbook" ? input.yearbookCycle ?? "calendar_year" : undefined,
    anniversaryDate:
      input.type === "yearbook" && input.yearbookCycle !== "calendar_year"
        ? input.anniversaryDate ?? input.startDate
        : undefined,
    ownerId: owner.id,
    members: [owner],
    invites: [
      {
        id: `invite-${titleSeed || "new"}`,
        name: owner.name,
        email: owner.email,
        role: "owner",
        status: "accepted",
        sentAt: new Date().toISOString(),
        acceptedAt: new Date().toISOString(),
        acceptedByUserId: owner.id,
      },
    ],
    notes: [],
    photos: [],
    faceClusters: [],
    resolutionTasks: [],
    bookThemes: cloneThemes(),
    selectedThemeId: editorialThemes[0].id,
    bookDraft: {
      id: `draft-${titleSeed || "new"}`,
      title: input.title,
      format: "12x12 square",
      status: "draft",
      themeId: editorialThemes[0].id,
      summary:
        "The draft book will appear here once uploads and memory notes give the layout engine enough material to curate a real first proof.",
      pages: [],
    },
    mockPrintOrder: {
      id: `order-${titleSeed || "new"}`,
      status: "draft",
      priceCents: 6400,
      shippingName: input.ownerName,
      shippingCity: "Not set yet",
      estimatedShipWindow: "5-7 business days",
      orderCode: `PBM-${(titleSeed || "NEW").toUpperCase().slice(0, 6)}`,
    },
  });
}
