export const FONT_PRESETS = [
  {
    id: "gallery",
    label: "Gallery serif",
    description: "Cormorant + Manrope",
    headline: 'var(--font-cormorant), "Cormorant Garamond", serif',
    body: 'var(--font-manrope), "Avenir Next", sans-serif',
  },
  {
    id: "modern",
    label: "Modern editorial",
    description: "Fraunces + Plus Jakarta Sans",
    headline: 'var(--font-fraunces), Georgia, serif',
    body: 'var(--font-plus-jakarta), "Segoe UI", sans-serif',
  },
  {
    id: "novel",
    label: "Novel classic",
    description: "Libre Baskerville + DM Sans",
    headline: 'var(--font-libre-baskerville), "Palatino Linotype", serif',
    body: 'var(--font-dm-sans), "Trebuchet MS", sans-serif',
  },
  {
    id: "journal",
    label: "Journal soft",
    description: "Lora + Work Sans",
    headline: 'var(--font-lora), "Baskerville", serif',
    body: 'var(--font-work-sans), "Helvetica Neue", sans-serif',
  },
  {
    id: "romantic",
    label: "Romantic feature",
    description: "Playfair Display + Nunito Sans",
    headline: 'var(--font-playfair), "Times New Roman", serif',
    body: 'var(--font-nunito), "Avenir Next", sans-serif',
  },
  {
    id: "outdoors",
    label: "Outdoor premium",
    description: "Newsreader + Inter",
    headline: 'var(--font-newsreader), Georgia, serif',
    body: 'var(--font-inter), "Segoe UI", sans-serif',
  },
  {
    id: "couture",
    label: "Couture classic",
    description: "Bodoni Moda + Source Sans 3",
    headline: 'var(--font-bodoni-moda), "Didot", serif',
    body: 'var(--font-source-sans-3), "Segoe UI", sans-serif',
  },
  {
    id: "field",
    label: "Field notes",
    description: "Spectral + Inter",
    headline: 'var(--font-spectral), Georgia, serif',
    body: 'var(--font-inter), "Segoe UI", sans-serif',
  },
  {
    id: "studio",
    label: "Studio clean",
    description: "Fraunces + Figtree",
    headline: 'var(--font-fraunces), Georgia, serif',
    body: 'var(--font-figtree), "Segoe UI", sans-serif',
  },
  {
    id: "continental",
    label: "Continental",
    description: "Prata + DM Sans",
    headline: 'var(--font-prata), Georgia, serif',
    body: 'var(--font-dm-sans), "Trebuchet MS", sans-serif',
  },
  {
    id: "poster",
    label: "Poster romance",
    description: "Abril Fatface + Assistant",
    headline: 'var(--font-abril-fatface), "Times New Roman", serif',
    body: 'var(--font-assistant), "Segoe UI", sans-serif',
  },
  {
    id: "alpine",
    label: "Alpine classic",
    description: "Merriweather + Montserrat",
    headline: 'var(--font-merriweather), Georgia, serif',
    body: 'var(--font-montserrat), "Segoe UI", sans-serif',
  },
  {
    id: "salon",
    label: "Salon",
    description: "Playfair Display + Source Sans 3",
    headline: 'var(--font-playfair), "Times New Roman", serif',
    body: 'var(--font-source-sans-3), "Segoe UI", sans-serif',
  },
  {
    id: "expedition",
    label: "Expedition",
    description: "Newsreader + Figtree",
    headline: 'var(--font-newsreader), Georgia, serif',
    body: 'var(--font-figtree), "Segoe UI", sans-serif',
  },
  {
    id: "grotesk",
    label: "Grotesk luxe",
    description: "Prata + Space Grotesk",
    headline: 'var(--font-prata), Georgia, serif',
    body: 'var(--font-space-grotesk), "Segoe UI", sans-serif',
  },
  {
    id: "artisan",
    label: "Artisan",
    description: "Bodoni Moda + Manrope",
    headline: 'var(--font-bodoni-moda), "Didot", serif',
    body: 'var(--font-manrope), "Avenir Next", sans-serif',
  },
] as const;

export type FontPresetId = (typeof FONT_PRESETS)[number]["id"];
